language: r
latex: false
fortran: false

matrix:
  include:
    - dist: trusty
      r: oldrel
    - dist: xenial
      env: R_CODECOV=true
    - os: osx
      brew_packages: jq
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    sources:
      - sourceline: 'ppa:cran/jq'
    packages:
      - libjq-dev

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: BH89TWt2sC+iF+j3uq0VhQ8weYKhi6/vgOU4Xu4fRnXFb37+lW9F7xI1LzBwhCFe2mri1b8bFF1IV1mFq6NVdkOHLg1/CF7J2C106yMO56zj8qes4KwZ7YHdU2shzYUKovi7uoDyGlUzsAYpKEe2VbL2bSMUQtdBh2nbI47CCu0=
